-- Pharmacy Connect Hub prototype schema for Supabase.
-- These grants and policies are intentionally broad so the current publishable-key prototype
-- can read and write through the existing Express API. Tighten them before production use.

create table if not exists public.wholesalers (
  id text primary key,
  name text not null,
  location text not null,
  rating numeric(2,1) not null check (rating >= 0 and rating <= 5),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.products (
  id text primary key,
  wholesaler_id text not null references public.wholesalers(id) on delete cascade,
  name text not null,
  generic text not null,
  strength text not null,
  pack_size text not null,
  price numeric(12,2) not null check (price > 0),
  stock integer not null check (stock >= 0),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.users (
  id text primary key,
  name text not null,
  email text not null unique,
  password text not null,
  role text not null check (role in ('pharmacy', 'supplier', 'admin')),
  wholesaler_id text references public.wholesalers(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.order_requests (
  id text primary key,
  customer_name text not null,
  customer_phone text not null,
  delivery_address text not null,
  status text not null check (
    status in (
      'Quote requested',
      'Quotes received',
      'Accepted',
      'Processing',
      'Dispatched',
      'Delivered'
    )
  ),
  accepted_quote_id text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.order_request_items (
  id bigint generated by default as identity primary key,
  order_request_id text not null references public.order_requests(id) on delete cascade,
  product_id text not null references public.products(id) on delete restrict,
  product_name text not null,
  generic text not null,
  strength text not null,
  pack_size text not null,
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.quotes (
  id text primary key,
  wholesaler_id text not null references public.wholesalers(id) on delete cascade,
  wholesaler_name text not null,
  order_request_id text not null references public.order_requests(id) on delete cascade,
  total numeric(12,2) not null check (total >= 0),
  status text not null check (status in ('Pending', 'Accepted', 'Rejected')),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.quote_items (
  id bigint generated by default as identity primary key,
  quote_id text not null references public.quotes(id) on delete cascade,
  product_id text not null references public.products(id) on delete restrict,
  product_name text not null,
  quoted_price numeric(12,2) not null check (quoted_price > 0),
  delivery_days integer not null check (delivery_days > 0),
  comment text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists products_wholesaler_id_idx on public.products (wholesaler_id);
create index if not exists users_role_idx on public.users (role);
create index if not exists users_wholesaler_id_idx on public.users (wholesaler_id);
create index if not exists order_requests_status_idx on public.order_requests (status);
create index if not exists order_requests_accepted_quote_id_idx on public.order_requests (accepted_quote_id);
create index if not exists order_request_items_order_request_id_idx on public.order_request_items (order_request_id);
create index if not exists order_request_items_product_id_idx on public.order_request_items (product_id);
create index if not exists quotes_order_request_id_idx on public.quotes (order_request_id);
create index if not exists quotes_wholesaler_id_idx on public.quotes (wholesaler_id);
create index if not exists quote_items_quote_id_idx on public.quote_items (quote_id);

grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;

alter table public.wholesalers enable row level security;
alter table public.products enable row level security;
alter table public.users enable row level security;
alter table public.order_requests enable row level security;
alter table public.order_request_items enable row level security;
alter table public.quotes enable row level security;
alter table public.quote_items enable row level security;

drop policy if exists "prototype full access" on public.wholesalers;
create policy "prototype full access" on public.wholesalers
  for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "prototype full access" on public.products;
create policy "prototype full access" on public.products
  for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "prototype full access" on public.users;
create policy "prototype full access" on public.users
  for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "prototype full access" on public.order_requests;
create policy "prototype full access" on public.order_requests
  for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "prototype full access" on public.order_request_items;
create policy "prototype full access" on public.order_request_items
  for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "prototype full access" on public.quotes;
create policy "prototype full access" on public.quotes
  for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "prototype full access" on public.quote_items;
create policy "prototype full access" on public.quote_items
  for all
  to anon, authenticated
  using (true)
  with check (true);
