-- Order amendments: read-only verification of every phase, in one result.
-- Run it in the SQL Editor of the PRODUCTION project (check the project name and the PRODUCTION badge first) and send the result back.
-- It only reads the catalog: it creates, changes and writes nothing. One row per phase; a phase that is fully applied shows
-- passed = checks and an empty "missing" column. A phase that is not applied (yet) lists what is missing.
WITH
  tbls AS (SELECT table_name::text AS name FROM information_schema.tables WHERE table_schema = 'public'),
  cols AS (SELECT table_name::text AS tbl, column_name::text AS col FROM information_schema.columns WHERE table_schema = 'public'),
  fns  AS (SELECT p.proname::text AS name, pg_get_functiondef(p.oid) AS def
           FROM pg_proc p WHERE p.pronamespace = 'public'::regnamespace AND p.prokind = 'f'),
  trgs AS (SELECT tgname::text AS name FROM pg_trigger WHERE NOT tgisinternal),
  idxs AS (SELECT indexname::text AS name FROM pg_indexes WHERE schemaname = 'public'),
  checks(phase, item, ok) AS (VALUES
  ('1 foundation', 'column orders.effective_total_ghs', EXISTS (SELECT 1 FROM cols WHERE tbl = 'orders' AND col = 'effective_total_ghs')),
  ('1 foundation', 'table order_events', EXISTS (SELECT 1 FROM tbls WHERE name = 'order_events')),
  ('1 foundation', 'function order_timeline', EXISTS (SELECT 1 FROM fns WHERE name = 'order_timeline')),
  ('1 foundation', 'function record_order_event', EXISTS (SELECT 1 FROM fns WHERE name = 'record_order_event')),
  ('1 foundation', 'function order_effective_total', EXISTS (SELECT 1 FROM fns WHERE name = 'order_effective_total')),
  ('1 foundation', 'column credit_ledger_entries.amendment_id', EXISTS (SELECT 1 FROM cols WHERE tbl = 'credit_ledger_entries' AND col = 'amendment_id')),
  ('1 foundation', 'column credit_ledger_entries.shipment_id', EXISTS (SELECT 1 FROM cols WHERE tbl = 'credit_ledger_entries' AND col = 'shipment_id')),
  ('1 foundation', 'index credit_ledger_amendment_entry_unique', EXISTS (SELECT 1 FROM idxs WHERE name = 'credit_ledger_amendment_entry_unique')),
  ('1 foundation', 'index credit_ledger_shipment_invoice_unique', EXISTS (SELECT 1 FROM idxs WHERE name = 'credit_ledger_shipment_invoice_unique')),
  ('1 foundation', 'trigger trg_order_events_append_only', EXISTS (SELECT 1 FROM trgs WHERE name = 'trg_order_events_append_only')),
  ('1 foundation', 'order-line guard lets the classification change (or the guard does not exist)', (NOT EXISTS (SELECT 1 FROM fns WHERE name = 'phase0_order_item_integrity') OR EXISTS (SELECT 1 FROM fns WHERE name = 'phase0_order_item_integrity' AND def LIKE '%purchase_category%'))),
  ('2 partial fulfilment', 'table order_amendments', EXISTS (SELECT 1 FROM tbls WHERE name = 'order_amendments')),
  ('2 partial fulfilment', 'table order_amendment_lines', EXISTS (SELECT 1 FROM tbls WHERE name = 'order_amendment_lines')),
  ('2 partial fulfilment', 'table order_amendment_messages', EXISTS (SELECT 1 FROM tbls WHERE name = 'order_amendment_messages')),
  ('2 partial fulfilment', 'table order_stock_movements', EXISTS (SELECT 1 FROM tbls WHERE name = 'order_stock_movements')),
  ('2 partial fulfilment', 'function apply_function_patch', EXISTS (SELECT 1 FROM fns WHERE name = 'apply_function_patch')),
  ('2 partial fulfilment', 'function _amendment_actor_label', EXISTS (SELECT 1 FROM fns WHERE name = '_amendment_actor_label')),
  ('2 partial fulfilment', 'function _amendment_money', EXISTS (SELECT 1 FROM fns WHERE name = '_amendment_money')),
  ('2 partial fulfilment', 'function propose_partial_fulfilment', EXISTS (SELECT 1 FROM fns WHERE name = 'propose_partial_fulfilment')),
  ('2 partial fulfilment', 'function respond_to_amendment', EXISTS (SELECT 1 FROM fns WHERE name = 'respond_to_amendment')),
  ('2 partial fulfilment', 'function answer_amendment_clarification', EXISTS (SELECT 1 FROM fns WHERE name = 'answer_amendment_clarification')),
  ('2 partial fulfilment', 'function withdraw_amendment', EXISTS (SELECT 1 FROM fns WHERE name = 'withdraw_amendment')),
  ('2 partial fulfilment', 'function get_order_amendments', EXISTS (SELECT 1 FROM fns WHERE name = 'get_order_amendments')),
  ('2 partial fulfilment', 'function order_supply_summary', EXISTS (SELECT 1 FROM fns WHERE name = 'order_supply_summary')),
  ('2 partial fulfilment', 'function order_item_supplied_qty', EXISTS (SELECT 1 FROM fns WHERE name = 'order_item_supplied_qty')),
  ('2 partial fulfilment', 'function order_amendment_stock_taken', EXISTS (SELECT 1 FROM fns WHERE name = 'order_amendment_stock_taken')),
  ('2 partial fulfilment', 'function order_has_stock_evidence', EXISTS (SELECT 1 FROM fns WHERE name = 'order_has_stock_evidence')),
  ('2 partial fulfilment', 'function send_amendment_reminders', EXISTS (SELECT 1 FROM fns WHERE name = 'send_amendment_reminders')),
  ('2 partial fulfilment', 'function block_dispatch_during_amendment', EXISTS (SELECT 1 FROM fns WHERE name = 'block_dispatch_during_amendment')),
  ('2 partial fulfilment', 'function withdraw_amendments_on_order_cancel', EXISTS (SELECT 1 FROM fns WHERE name = 'withdraw_amendments_on_order_cancel')),
  ('2 partial fulfilment', 'trigger trg_block_dispatch_during_amendment', EXISTS (SELECT 1 FROM trgs WHERE name = 'trg_block_dispatch_during_amendment')),
  ('2 partial fulfilment', 'trigger trg_withdraw_amendments_on_order_cancel', EXISTS (SELECT 1 FROM trgs WHERE name = 'trg_withdraw_amendments_on_order_cancel')),
  ('2 partial fulfilment', 'trigger trg_order_amendments_protect', EXISTS (SELECT 1 FROM trgs WHERE name = 'trg_order_amendments_protect')),
  ('2 partial fulfilment', 'trigger trg_order_amendment_lines_append_only', EXISTS (SELECT 1 FROM trgs WHERE name = 'trg_order_amendment_lines_append_only')),
  ('2 partial fulfilment', 'trigger trg_order_stock_movements_append_only', EXISTS (SELECT 1 FROM trgs WHERE name = 'trg_order_stock_movements_append_only')),
  ('2 partial fulfilment', 'index order_amendments_one_open_per_order', EXISTS (SELECT 1 FROM idxs WHERE name = 'order_amendments_one_open_per_order')),
  ('2 partial fulfilment', 'credit_invoice_status contains amendment_id IS NOT NULL', EXISTS (SELECT 1 FROM fns WHERE name = 'credit_invoice_status' AND def LIKE '%amendment_id IS NOT NULL%')),
  ('6 readers use effective totals', 'function apply_function_regex_patch', EXISTS (SELECT 1 FROM fns WHERE name = 'apply_function_regex_patch')),
  ('6 readers use effective totals', 'function order_receipt_supply', EXISTS (SELECT 1 FROM fns WHERE name = 'order_receipt_supply')),
  ('6 readers use effective totals', 'pharmacy_report_orders contains effective_total_ghs', EXISTS (SELECT 1 FROM fns WHERE name = 'pharmacy_report_orders' AND def LIKE '%effective_total_ghs%')),
  ('6 readers use effective totals', 'admin_report_sales contains effective_total_ghs', EXISTS (SELECT 1 FROM fns WHERE name = 'admin_report_sales' AND def LIKE '%effective_total_ghs%')),
  ('6 readers use effective totals', 'wholesaler_report_overview contains effective_total_ghs', EXISTS (SELECT 1 FROM fns WHERE name = 'wholesaler_report_overview' AND def LIKE '%effective_total_ghs%')),
  ('6 readers use effective totals', 'list_pharmacy_order_history contains effective_total_ghs', EXISTS (SELECT 1 FROM fns WHERE name = 'list_pharmacy_order_history' AND def LIKE '%effective_total_ghs%')),
  ('6 readers use effective totals', 'wholesaler_customers contains effective_total_ghs', EXISTS (SELECT 1 FROM fns WHERE name = 'wholesaler_customers' AND def LIKE '%effective_total_ghs%')),
  ('6 readers use effective totals', 'customer_statement contains ''adjustment''', EXISTS (SELECT 1 FROM fns WHERE name = 'customer_statement' AND def LIKE '%''adjustment''%')),
  ('3 back-orders', 'table order_shipments', EXISTS (SELECT 1 FROM tbls WHERE name = 'order_shipments')),
  ('3 back-orders', 'table order_shipment_lines', EXISTS (SELECT 1 FROM tbls WHERE name = 'order_shipment_lines')),
  ('3 back-orders', 'table order_backorder_cancellations', EXISTS (SELECT 1 FROM tbls WHERE name = 'order_backorder_cancellations')),
  ('3 back-orders', 'function order_item_fulfilled_qty', EXISTS (SELECT 1 FROM fns WHERE name = 'order_item_fulfilled_qty')),
  ('3 back-orders', 'function order_item_shipment_qty', EXISTS (SELECT 1 FROM fns WHERE name = 'order_item_shipment_qty')),
  ('3 back-orders', 'function order_item_backordered_qty', EXISTS (SELECT 1 FROM fns WHERE name = 'order_item_backordered_qty')),
  ('3 back-orders', 'function order_item_backorder_outstanding', EXISTS (SELECT 1 FROM fns WHERE name = 'order_item_backorder_outstanding')),
  ('3 back-orders', 'function order_backorder_state', EXISTS (SELECT 1 FROM fns WHERE name = 'order_backorder_state')),
  ('3 back-orders', 'function create_backorder_shipment', EXISTS (SELECT 1 FROM fns WHERE name = 'create_backorder_shipment')),
  ('3 back-orders', 'function advance_backorder_shipment', EXISTS (SELECT 1 FROM fns WHERE name = 'advance_backorder_shipment')),
  ('3 back-orders', 'function cancel_backorder_shipment', EXISTS (SELECT 1 FROM fns WHERE name = 'cancel_backorder_shipment')),
  ('3 back-orders', 'function cancel_backorder_remaining', EXISTS (SELECT 1 FROM fns WHERE name = 'cancel_backorder_remaining')),
  ('3 back-orders', 'function get_order_backorder', EXISTS (SELECT 1 FROM fns WHERE name = 'get_order_backorder')),
  ('3 back-orders', 'function close_backorder_on_order_cancel', EXISTS (SELECT 1 FROM fns WHERE name = 'close_backorder_on_order_cancel')),
  ('3 back-orders', 'function protect_effective_total', EXISTS (SELECT 1 FROM fns WHERE name = 'protect_effective_total')),
  ('3 back-orders', 'function _allow_order_total_change', EXISTS (SELECT 1 FROM fns WHERE name = '_allow_order_total_change')),
  ('3 back-orders', 'trigger trg_protect_effective_total', EXISTS (SELECT 1 FROM trgs WHERE name = 'trg_protect_effective_total')),
  ('3 back-orders', 'trigger trg_close_backorder_on_order_cancel', EXISTS (SELECT 1 FROM trgs WHERE name = 'trg_close_backorder_on_order_cancel')),
  ('3 back-orders', 'trigger trg_order_shipments_protect', EXISTS (SELECT 1 FROM trgs WHERE name = 'trg_order_shipments_protect')),
  ('3 back-orders', 'index order_stock_movements_shipment_once', EXISTS (SELECT 1 FROM idxs WHERE name = 'order_stock_movements_shipment_once')),
  ('3 back-orders', 'pharmacy_report_products contains order_item_fulfilled_qty', EXISTS (SELECT 1 FROM fns WHERE name = 'pharmacy_report_products' AND def LIKE '%order_item_fulfilled_qty%')),
  ('3 back-orders', 'order_supply_summary contains main_total_ghs', EXISTS (SELECT 1 FROM fns WHERE name = 'order_supply_summary' AND def LIKE '%main_total_ghs%')),
  ('3 back-orders', 'respond_to_amendment contains accept_backorder', EXISTS (SELECT 1 FROM fns WHERE name = 'respond_to_amendment' AND def LIKE '%accept_backorder%')),
  ('3 back-orders', 'customer_statement contains ''shipment''', EXISTS (SELECT 1 FROM fns WHERE name = 'customer_statement' AND def LIKE '%''shipment''%')),
  ('5 delivery reconciliation', 'table order_delivery_reports', EXISTS (SELECT 1 FROM tbls WHERE name = 'order_delivery_reports')),
  ('5 delivery reconciliation', 'table order_delivery_report_lines', EXISTS (SELECT 1 FROM tbls WHERE name = 'order_delivery_report_lines')),
  ('5 delivery reconciliation', 'table order_delivery_report_decisions', EXISTS (SELECT 1 FROM tbls WHERE name = 'order_delivery_report_decisions')),
  ('5 delivery reconciliation', 'column order_returns.delivery_report_id', EXISTS (SELECT 1 FROM cols WHERE tbl = 'order_returns' AND col = 'delivery_report_id')),
  ('5 delivery reconciliation', 'column credit_ledger_entries.delivery_report_id', EXISTS (SELECT 1 FROM cols WHERE tbl = 'credit_ledger_entries' AND col = 'delivery_report_id')),
  ('5 delivery reconciliation', 'column credit_ledger_entries.return_id', EXISTS (SELECT 1 FROM cols WHERE tbl = 'credit_ledger_entries' AND col = 'return_id')),
  ('5 delivery reconciliation', 'function order_item_reconciled_qty', EXISTS (SELECT 1 FROM fns WHERE name = 'order_item_reconciled_qty')),
  ('5 delivery reconciliation', 'function submit_delivery_report', EXISTS (SELECT 1 FROM fns WHERE name = 'submit_delivery_report')),
  ('5 delivery reconciliation', 'function withdraw_delivery_report', EXISTS (SELECT 1 FROM fns WHERE name = 'withdraw_delivery_report')),
  ('5 delivery reconciliation', 'function resolve_delivery_report', EXISTS (SELECT 1 FROM fns WHERE name = 'resolve_delivery_report')),
  ('5 delivery reconciliation', 'function get_order_delivery_reports', EXISTS (SELECT 1 FROM fns WHERE name = 'get_order_delivery_reports')),
  ('5 delivery reconciliation', 'index order_delivery_reports_one_live', EXISTS (SELECT 1 FROM idxs WHERE name = 'order_delivery_reports_one_live')),
  ('5 delivery reconciliation', 'index credit_ledger_delivery_report_entry_unique', EXISTS (SELECT 1 FROM idxs WHERE name = 'credit_ledger_delivery_report_entry_unique')),
  ('5 delivery reconciliation', 'index credit_ledger_return_entry_unique', EXISTS (SELECT 1 FROM idxs WHERE name = 'credit_ledger_return_entry_unique')),
  ('5 delivery reconciliation', 'resolve_order_return contains return_id', EXISTS (SELECT 1 FROM fns WHERE name = 'resolve_order_return' AND def LIKE '%return_id%')),
  ('5 delivery reconciliation', 'credit_invoice_status contains delivery_report_id IS NOT NULL', EXISTS (SELECT 1 FROM fns WHERE name = 'credit_invoice_status' AND def LIKE '%delivery_report_id IS NOT NULL%')),
  ('5 delivery reconciliation', 'get_returnable_items contains order_item_reconciled_qty', EXISTS (SELECT 1 FROM fns WHERE name = 'get_returnable_items' AND def LIKE '%order_item_reconciled_qty%')),
  ('5 delivery reconciliation', 'customer_statement contains delivery_credit', EXISTS (SELECT 1 FROM fns WHERE name = 'customer_statement' AND def LIKE '%delivery_credit%')),
  ('4 price amendments', 'column order_amendment_lines.proposed_unit_price_ghs', EXISTS (SELECT 1 FROM cols WHERE tbl = 'order_amendment_lines' AND col = 'proposed_unit_price_ghs')),
  ('4 price amendments', 'response choice accept_price allowed', EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'order_amendments_response_choice_check' AND pg_get_constraintdef(oid) LIKE '%accept_price%')),
  ('4 price amendments', 'function order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'order_item_effective_price')),
  ('4 price amendments', 'function propose_price_amendment', EXISTS (SELECT 1 FROM fns WHERE name = 'propose_price_amendment')),
  ('4 price amendments', 'function respond_to_price_amendment', EXISTS (SELECT 1 FROM fns WHERE name = 'respond_to_price_amendment')),
  ('4 price amendments', 'function answer_price_clarification', EXISTS (SELECT 1 FROM fns WHERE name = 'answer_price_clarification')),
  ('4 price amendments', 'function withdraw_price_amendment', EXISTS (SELECT 1 FROM fns WHERE name = 'withdraw_price_amendment')),
  ('4 price amendments', 'propose_partial_fulfilment contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'propose_partial_fulfilment' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'create_backorder_shipment contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'create_backorder_shipment' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'submit_delivery_report contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'submit_delivery_report' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'request_order_return contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'request_order_return' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'get_returnable_items contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'get_returnable_items' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'get_order_amendments contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'get_order_amendments' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'get_order_backorder contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'get_order_backorder' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'get_order_delivery_reports contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'get_order_delivery_reports' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'pharmacy_report_products contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'pharmacy_report_products' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'pharmacy_report_purchases contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'pharmacy_report_purchases' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'pharmacy_report_purchases_summary contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'pharmacy_report_purchases_summary' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'wholesaler_report_products contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'wholesaler_report_products' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'wholesaler_customer_detail contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'wholesaler_customer_detail' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'pharmacy_price_history contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'pharmacy_price_history' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'pharmacy_price_history_detail contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'pharmacy_price_history_detail' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'order_supply_summary contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'order_supply_summary' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'order_receipt_supply contains order_item_effective_price', EXISTS (SELECT 1 FROM fns WHERE name = 'order_receipt_supply' AND def LIKE '%order_item_effective_price%')),
  ('4 price amendments', 'customer_statement contains price_adjustment', EXISTS (SELECT 1 FROM fns WHERE name = 'customer_statement' AND def LIKE '%price_adjustment%')),
  ('4 price amendments', 'withdraw_amendment contains Use the price proposal actions', EXISTS (SELECT 1 FROM fns WHERE name = 'withdraw_amendment' AND def LIKE '%Use the price proposal actions%')),
  ('4 price amendments', 'answer_amendment_clarification contains Use the price proposal actions', EXISTS (SELECT 1 FROM fns WHERE name = 'answer_amendment_clarification' AND def LIKE '%Use the price proposal actions%')),
  ('3b cash back-orders', 'table order_collections', EXISTS (SELECT 1 FROM tbls WHERE name = 'order_collections')),
  ('3b cash back-orders', 'function order_has_cash_portions', EXISTS (SELECT 1 FROM fns WHERE name = 'order_has_cash_portions')),
  ('3b cash back-orders', 'function order_main_total', EXISTS (SELECT 1 FROM fns WHERE name = 'order_main_total')),
  ('3b cash back-orders', 'function order_shipment_net', EXISTS (SELECT 1 FROM fns WHERE name = 'order_shipment_net')),
  ('3b cash back-orders', 'function order_shipments_net', EXISTS (SELECT 1 FROM fns WHERE name = 'order_shipments_net')),
  ('3b cash back-orders', 'function confirm_cash_collection', EXISTS (SELECT 1 FROM fns WHERE name = 'confirm_cash_collection')),
  ('3b cash back-orders', 'function cash_collection_receipt', EXISTS (SELECT 1 FROM fns WHERE name = 'cash_collection_receipt')),
  ('3b cash back-orders', 'function mark_collection_receipt_sent', EXISTS (SELECT 1 FROM fns WHERE name = 'mark_collection_receipt_sent')),
  ('3b cash back-orders', 'function _can_collect_cash', EXISTS (SELECT 1 FROM fns WHERE name = '_can_collect_cash')),
  ('3b cash back-orders', 'function guard_cash_portion_payment', EXISTS (SELECT 1 FROM fns WHERE name = 'guard_cash_portion_payment')),
  ('3b cash back-orders', 'trigger trg_guard_cash_portion_payment', EXISTS (SELECT 1 FROM trgs WHERE name = 'trg_guard_cash_portion_payment')),
  ('3b cash back-orders', 'trigger trg_order_collections_protect', EXISTS (SELECT 1 FROM trgs WHERE name = 'trg_order_collections_protect')),
  ('3b cash back-orders', 'index order_collections_main_unique', EXISTS (SELECT 1 FROM idxs WHERE name = 'order_collections_main_unique')),
  ('3b cash back-orders', 'index order_collections_shipment_unique', EXISTS (SELECT 1 FROM idxs WHERE name = 'order_collections_shipment_unique')),
  ('3b cash back-orders', 'cash orders may take the back-order choice', EXISTS (SELECT 1 FROM fns WHERE name = 'respond_to_amendment' AND def NOT LIKE '%Back-orders are only available on credit orders for now. Accept%')),
  ('3b cash back-orders', 'order_receipt_supply contains order_main_total', EXISTS (SELECT 1 FROM fns WHERE name = 'order_receipt_supply' AND def LIKE '%order_main_total%')),
  ('3b cash back-orders', 'order_backorder_state contains cash_portions', EXISTS (SELECT 1 FROM fns WHERE name = 'order_backorder_state' AND def LIKE '%cash_portions%')),
  ('3b cash back-orders', 'get_order_backorder contains main_collected_at', EXISTS (SELECT 1 FROM fns WHERE name = 'get_order_backorder' AND def LIKE '%main_collected_at%')),
  ('3b cash back-orders', 'customer_statement contains order_collections', EXISTS (SELECT 1 FROM fns WHERE name = 'customer_statement' AND def LIKE '%order_collections%')),
  ('3b cash back-orders', 'resolve_delivery_report contains order_collections', EXISTS (SELECT 1 FROM fns WHERE name = 'resolve_delivery_report' AND def LIKE '%order_collections%')),
  ('3b cash back-orders', 'order_supply_summary contains order_shipments_net', EXISTS (SELECT 1 FROM fns WHERE name = 'order_supply_summary' AND def LIKE '%order_shipments_net%')),
  ('3b cash back-orders', 'advance_backorder_shipment contains order_collections', EXISTS (SELECT 1 FROM fns WHERE name = 'advance_backorder_shipment' AND def LIKE '%order_collections%'))
  )
SELECT phase,
       count(*) AS checks,
       count(*) FILTER (WHERE ok) AS passed,
       COALESCE(string_agg(item, '; ') FILTER (WHERE NOT ok), '') AS missing
FROM checks
GROUP BY phase
ORDER BY phase;
