/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WholesalerRouteImport } from './routes/wholesaler'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddBusinessRouteImport } from './routes/add-business'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WholesalerReportsRouteImport } from './routes/wholesaler_.reports'
import { Route as PharmacyReportsRouteImport } from './routes/pharmacy_.reports'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'

const WholesalerRoute = WholesalerRouteImport.update({
  id: '/wholesaler',
  path: '/wholesaler',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBusinessRoute = AddBusinessRouteImport.update({
  id: '/add-business',
  path: '/add-business',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesalerReportsRoute = WholesalerReportsRouteImport.update({
  id: '/wholesaler_/reports',
  path: '/wholesaler/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyReportsRoute = PharmacyReportsRouteImport.update({
  id: '/pharmacy_/reports',
  path: '/pharmacy/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-business': typeof AddBusinessRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pharmacy': typeof PharmacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/wholesaler': typeof WholesalerRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/pharmacy/reports': typeof PharmacyReportsRoute
  '/wholesaler/reports': typeof WholesalerReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-business': typeof AddBusinessRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pharmacy': typeof PharmacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/wholesaler': typeof WholesalerRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/pharmacy/reports': typeof PharmacyReportsRoute
  '/wholesaler/reports': typeof WholesalerReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-business': typeof AddBusinessRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pharmacy': typeof PharmacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/wholesaler': typeof WholesalerRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/pharmacy_/reports': typeof PharmacyReportsRoute
  '/wholesaler_/reports': typeof WholesalerReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-business'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/pharmacy'
    | '/reset-password'
    | '/signup'
    | '/staff'
    | '/wholesaler'
    | '/admin/activity'
    | '/admin/reports'
    | '/admin/staff'
    | '/pharmacy/reports'
    | '/wholesaler/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-business'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/pharmacy'
    | '/reset-password'
    | '/signup'
    | '/staff'
    | '/wholesaler'
    | '/admin/activity'
    | '/admin/reports'
    | '/admin/staff'
    | '/pharmacy/reports'
    | '/wholesaler/reports'
  id:
    | '__root__'
    | '/'
    | '/add-business'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/pharmacy'
    | '/reset-password'
    | '/signup'
    | '/staff'
    | '/wholesaler'
    | '/admin/activity'
    | '/admin/reports'
    | '/admin/staff'
    | '/pharmacy_/reports'
    | '/wholesaler_/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddBusinessRoute: typeof AddBusinessRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PharmacyRoute: typeof PharmacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StaffRoute: typeof StaffRoute
  WholesalerRoute: typeof WholesalerRoute
  PharmacyReportsRoute: typeof PharmacyReportsRoute
  WholesalerReportsRoute: typeof WholesalerReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wholesaler': {
      id: '/wholesaler'
      path: '/wholesaler'
      fullPath: '/wholesaler'
      preLoaderRoute: typeof WholesalerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-business': {
      id: '/add-business'
      path: '/add-business'
      fullPath: '/add-business'
      preLoaderRoute: typeof AddBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesaler_/reports': {
      id: '/wholesaler_/reports'
      path: '/wholesaler/reports'
      fullPath: '/wholesaler/reports'
      preLoaderRoute: typeof WholesalerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy_/reports': {
      id: '/pharmacy_/reports'
      path: '/pharmacy/reports'
      fullPath: '/pharmacy/reports'
      preLoaderRoute: typeof PharmacyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStaffRoute: typeof AdminStaffRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStaffRoute: AdminStaffRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddBusinessRoute: AddBusinessRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PharmacyRoute: PharmacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StaffRoute: StaffRoute,
  WholesalerRoute: WholesalerRoute,
  PharmacyReportsRoute: PharmacyReportsRoute,
  WholesalerReportsRoute: WholesalerReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
